### PR TITLE
CHG printf is not fprintf

### PR DESCRIPTION
**Pull request by PIG208**
More stuff to undergrad-dev

### CODE REVIEW

**Comment by PIG208** [comment]
Hopefully, we can get this merged into AnubisLMS/xv6 soon. I stacked this on your dev branch so as to avoid future merge conflicts @nickelpro.

**Comment by nickelpro** [comment]
I have commit access for upstream and rebasing isn't a problem for me. Feel free to PR this stuff upstream

**Comment by PIG208** [comment]
Gotcha

**Comment by PIG208** [comment]
Superseded by AnubisLMS/xv6#16.

**Pull request closed without merging**
